#!/usr/bin/env node
/* eslint no-var: 0, camelcase: 0, vars-on-top: 0 */

var child_process = require('child_process');
var async = require('async');

var maxTries = 3;
var wait = 2 * 1000;
var syncTries = 0;
var modifyTries = 0;

/**
 * Sync the deploy path and invalidate the CDN cache
 */
function run(cb) {
  syncTries++;

  console.log('-------------');
  console.log(' Try: ' + syncTries);
  console.log('-------------');

  var kid = child_process.spawn(process.argv[2], process.argv.slice(3), {
    encoding: 'utf8'
  });

  kid.stdout.pipe(process.stdout);
  kid.stderr.pipe(process.stdout);

  kid.on('close', function(code) {
    return cb(code);
  });
}

if (process.argv.length < 3) {
  console.error('ERROR: No command found');
  process.exit(70);
}

async.auto({
  run: async.retry({ times: maxTries, interval: wait }, run),
}, function(err) {
  if (err) {
    console.error('ERROR: Command filed after ' + maxTries + ' tries.');
    process.exit(70);
  }
});
